PROJECT_ADDED = "Чудово, проект успішно доданий!"
INCORRECT_DATE = "Некорректно введена дата, спробуйте знову."
DATE_ADDED = "Дата успішно добавлена"
INCORRECT_DURATION = "Тривалість повинна бути числом"
DURATION_ADDED = "Тривалість добавлена"
NAME_ADDED = "Им'я добавлено"
PHONE_ADDED = "Телефон добавлений"
COMMENT_ADDED = "Комментар добавлений"
